---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/ben/Code/Sysc4001/render'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: __render_create_surface, symObjAddr: 0x0, symBinAddr: 0x100003790, symSize: 0x180 }
  - { offsetInCU: 0x88, offset: 0x88, size: 0x8, addend: 0x0, symName: __render_create_surface, symObjAddr: 0x0, symBinAddr: 0x100003790, symSize: 0x180 }
  - { offsetInCU: 0xCC, offset: 0xCC, size: 0x8, addend: 0x0, symName: __render_clear_surface, symObjAddr: 0x180, symBinAddr: 0x100003910, symSize: 0xA0 }
  - { offsetInCU: 0x128, offset: 0x128, size: 0x8, addend: 0x0, symName: __render_delete_surface, symObjAddr: 0x220, symBinAddr: 0x1000039B0, symSize: 0x40 }
  - { offsetInCU: 0x14C, offset: 0x14C, size: 0x8, addend: 0x0, symName: __render_write_string, symObjAddr: 0x260, symBinAddr: 0x1000039F0, symSize: 0xF0 }
  - { offsetInCU: 0x1E0, offset: 0x1E0, size: 0x8, addend: 0x0, symName: __render_write_int, symObjAddr: 0x350, symBinAddr: 0x100003AE0, symSize: 0x130 }
  - { offsetInCU: 0x283, offset: 0x283, size: 0x8, addend: 0x0, symName: __render_display_frame, symObjAddr: 0x480, symBinAddr: 0x100003C10, symSize: 0x100 }
  - { offsetInCU: 0x2DF, offset: 0x2DF, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x580, symBinAddr: 0x100003D10, symSize: 0x192 }
...
